-- Schema for induct_events_na
CREATE TABLE induct_events_na (
  entity_id VARCHAR,
  entity_id_type VARCHAR,
  entity_type VARCHAR,
  event_type VARCHAR,
  event_reason VARCHAR,
  destination_id VARCHAR,
  destination_type VARCHAR,
  operation_node_id VARCHAR,
  operator_id VARCHAR,
  operator_type VARCHAR,
  event_time TIMESTAMP,
  is_routing_update_req VARCHAR,
  is_conveyed VARCHAR,
  chute_id VARCHAR,
  route_id VARCHAR,
  cycle_id VARCHAR,
  route_code VARCHAR,
  package_category VARCHAR,
  dw_created_time TIMESTAMP,
  tracking_id VARCHAR,
  node_id VARCHAR,
  label_type VARCHAR,
  delivery_assist_marker VARCHAR,
  sort_location VARCHAR,
  cycle_name VARCHAR,
  unloaded_at TIMESTAMP
);
