-- Schema for package_systems_event_na
CREATE TABLE package_systems_event_na (
  type VARCHAR,
  package_id VARCHAR,
  package_id_type VARCHAR,
  forward_amazon_barcode VARCHAR,
  forward_tracking_id VARCHAR,
  forward_tcda_container_id VARCHAR,
  state_location_type VARCHAR,
  state_location_id VARCHAR,
  state_location_destination_id VARCHAR,
  state_location_source_id VARCHAR,
  state_status VARCHAR,
  state_time TIMESTAMP,
  triggerer_id VARCHAR,
  triggerer_id_type VARCHAR,
  dw_created_time TIMESTAMP,
  state_sub_status VARCHAR,
  comp_type VARCHAR,
  comp_reason VARCHAR,
  comp_state VARCHAR,
  reverse_amazon_barcode VARCHAR,
  reverse_tcda_container_id VARCHAR,
  reverse_tracking_id VARCHAR,
  execution_id VARCHAR,
  execution_id_type VARCHAR,
  state_location_destination_type VARCHAR,
  state_location_source_type VARCHAR,
  unloaded_at TIMESTAMP
);
