#!/bin/bash
# Script to set up remote Claude connection

# Instructions for setting up connection to Claude on WSL from virtual desktop

echo "======================================================"
echo "  HOW TO CONNECT TO CLAUDE ON WSL FROM VIRTUAL DESKTOP"
echo "======================================================"
echo ""
echo "Claude is running a local server on port 35266 on your WSL instance."
echo "The Claude server uses WebSocket protocol and requires authentication."
echo ""
echo "Authentication Token: 0595a2a0-d1b5-4cd4-bd6d-d6557cfb15c8"
echo ""
echo "OPTION 1: SSH REMOTE PORT FORWARDING (RECOMMENDED)"
echo "--------------------------------------------------------------"
echo "1. From your virtual desktop, run this command to create a tunnel:"
echo "   ssh -R 35266:localhost:35266 your-wsl-username@your-wsl-hostname"
echo ""
echo "   Replace:"
echo "   - your-wsl-username: Your username on the WSL machine (admsia)"
echo "   - your-wsl-hostname: Your WSL machine's hostname (SEA-1802220383)"
echo ""
echo "   For example:"
echo "   ssh -R 35266:localhost:35266 admsia@SEA-1802220383"
echo ""
echo "2. Once connected via SSH, you can access Claude on your virtual desktop by:"
echo "   a. Setting up a local claude-client that points to localhost:35266"
echo "   b. Using the same authentication token shown above"
echo ""
echo "OPTION 2: INSTALL CLAUDE CLI ON VIRTUAL DESKTOP"
echo "--------------------------------------------------------------"
echo "If possible, installing the Claude CLI directly on your virtual desktop"
echo "would be simpler. You would need to ensure it's configured with the same"
echo "authentication credentials as your WSL instance."
echo ""
echo "IMPORTANT NOTES:"
echo "- The SSH tunnel must remain active while you're using Claude"
echo "- You may need to modify your .claude/config file on the virtual desktop"
echo "  to point to the forwarded port and use the same authentication token"
echo "- These commands create temporary tunnels that last only as long as the SSH connection"
echo ""
echo "To check if the Claude server is running on WSL:"
echo "ps aux | grep claude"
echo ""
echo "If the server isn't running, start it with:"
echo "claude"
echo ""
